image : microsoft/dotnet:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - test
  - release

build:
  stage: build
  script:
    - dotnet build

test:
  stage: test
  script:
    - dotnet test

release:
  stage: release
  only:
    - master
  artifacts:
    paths:
      - publish/
  script:
    - dotnet publish -c Release -o ../publish Authentication.Host/Authentication.Host.csproj
